server:
  port: ${SERVER_PORT:2333}
  address: 0.0.0.0

lavalink:
  plugins:
    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.1.1"
      snapshot: false
      
  server:
    password: "${LAVALINK_PASSWORD:UtaUtaDj}"
    sources:
      youtube: true      # ✅ CRITICAL: This must be enabled for LavaSrc to work
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false
    filters:
      volume: true
      equalizer: true
      karaoke: true
      timescale: true
      tremolo: true
      vibrato: true
      distortion: true
      rotation: true
      channelMix: true
      lowPass: true
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    youtubePlaylistLoadLimit: 6
    playerUpdateInterval: 5
    youtubeSearchEnabled: true    # ✅ CRITICAL: This must be true
    soundcloudSearchEnabled: true
    gc-warnings: false
    trackStuckThresholdMs: 10000
    useSeekGhosting: true

plugins:
  lavasrc:
    providers:
      - "ytsearch:%QUERY%"     # ✅ YouTube search first
      - "scsearch:%QUERY%"     # ✅ SoundCloud search second
    sources:
      spotify: true
      applemusic: false
      deezer: false
      yandexmusic: false
      flowerytts: false
      youtube: true            # ✅ CRITICAL: Must match server.sources.youtube
      soundcloud: true
    spotify:
      clientId: "${SPOTIFY_CLIENT_ID:c4d02b672c154189a2bc9401297873e5}"
      clientSecret: "${SPOTIFY_CLIENT_SECRET:5ff525521dba448b9cd6c1638010b783}"
      countryCode: "${SPOTIFY_COUNTRY_CODE:US}"
      playlistLoadLimit: 10
      albumLoadLimit: 10
    soundcloud:
      clientId: "iZIs9mchVcX5lhVRyQGGAYlNPVldzAoX"

metrics:
  prometheus:
    enabled: false

sentry:
  dsn: ""

logging:
  level:
    root: INFO
    lavalink: INFO
    com.sedmelluq.discord.lavaplayer: INFO
    com.github.topi314.lavasrc: INFO
  logback:
    rollingpolicy:
      max-file-size: 25MB
      max-history: 8
