server:
  port: ${SERVER_PORT:2333}
  address: 0.0.0.0

lavalink:
  plugins:
    # Using the correct dependency format for YouTube plugin 1.5.2
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.5.2"
      repository: "https://maven.lavalink.dev/releases"
      
  server:
    password: "${LAVALINK_PASSWORD:UtaUtaDj}"
    sources:
      # IMPORTANT: Disable built-in YouTube source when using the plugin
      youtube: false
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false
    filters:
      volume: true
      equalizer: true
      karaoke: true
      timescale: true
      tremolo: true
      vibrato: true
      distortion: true
      rotation: true
      channelMix: true
      lowPass: true
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    trackStuckThresholdMs: 30000
    youtubePlaylistLoadLimit: 6
    playerUpdateInterval: 5
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: false
    useSeekGhosting: true

# YouTube plugin configuration - this is the critical part
plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    # These clients are confirmed working as of the search results
    clients:
      - MUSIC
      - WEB
      - TVHTML5EMBEDDED
      - ANDROID_TESTSUITE
    # Disable OAuth initially to avoid complexity
    oauth:
      enabled: false

metrics:
  prometheus:
    enabled: false

sentry:
  dsn: ""

logging:
  level:
    root: INFO
    lavalink: INFO
    com.sedmelluq.discord.lavaplayer: INFO
    dev.lavalink.youtube: DEBUG  # This will help debug YouTube issues
  logback:
    rollingpolicy:
      max-file-size: 25MB
      max-history: 8
