server:
  port: ${SERVER_PORT:2333}
  address: 0.0.0.0

lavalink:
  server:
    password: "${LAVALINK_PASSWORD:UtaUtaDj}"
    sources:
      # CRITICAL: HTTP source must be enabled for radio streams
      http: true
      youtube: true
      soundcloud: true
      bandcamp: true
      twitch: false
      vimeo: false
      local: false
    filters:
      volume: true
      equalizer: true
      karaoke: true
      timescale: true
      tremolo: true
      vibrato: true
      distortion: true
      rotation: true
      channelMix: true
      lowPass: true
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    trackStuckThresholdMs: 10000
    youtubePlaylistLoadLimit: 6
    playerUpdateInterval: 5
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: false
    useSeekGhosting: true
    # HTTP configuration for radio streams
    httpConfig:
      proxyHost: ""
      proxyPort: 0
      proxyUser: ""
      proxyPassword: ""

# Plugins configuration
plugins: {}

# Metrics
metrics:
  prometheus:
    enabled: false

sentry:
  dsn: ""

# Enhanced logging to debug HTTP issues
logging:
  level:
    root: INFO
    lavalink: DEBUG
    com.sedmelluq.discord.lavaplayer: DEBUG
    com.sedmelluq.discord.lavaplayer.source.http: DEBUG
  logback:
    rollingpolicy:
      max-file-size: 25MB
      max-history: 8
