server:
  port: ${SERVER_PORT:2333}
  address: 0.0.0.0

lavalink:
  server:
    password: "${LAVALINK_PASSWORD:UtaUtaDj}"
    sources:
      youtube: false
      bandcamp: false
      soundcloud: false
      twitch: false
      vimeo: false
      http: true
      local: false
    filters:
      volume: true
      equalizer: true
      karaoke: true
      timescale: true
      tremolo: true
      vibrato: true
      distortion: true
      rotation: true
      channelMix: true
      lowPass: true
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    trackStuckThresholdMs: 10000
    youtubePlaylistLoadLimit: 6
    playerUpdateInterval: 5
    youtubeSearchEnabled: false
    soundcloudSearchEnabled: false
    gc-warnings: false
    useSeekGhosting: true

metrics:
  prometheus:
    enabled: false

sentry:
  dsn: ""

logging:
  level:
    root: INFO
    lavalink: INFO
    com.sedmelluq.discord.lavaplayer: INFO
  logback:
    rollingpolicy:
      max-file-size: 25MB
      max-history: 8
