server:
  port: ${SERVER_PORT:2333}
  address: 0.0.0.0
  http2:
    enabled: false # Disable HTTP/2 for better compatibility

spring:
  main:
    banner-mode: log
    
lavalink:
  plugins:
    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.2.0"
      snapshot: false
    - dependency: "com.github.topi314.lavasearch:lavasearch-plugin:1.0.0"
      snapshot: false
      
  server:
    password: "${LAVALINK_PASSWORD:UtaUtaDj}"
    sources:
      youtube: false # Disable to prioritize other sources
      youtube-music: false
      soundcloud: true # Keep SoundCloud enabled
      bandcamp: true
      twitch: false
      vimeo: false
      http: true
      local: false
    filters:
      volume: true
      equalizer: true
      karaoke: true
      timescale: true
      tremolo: true
      vibrato: true
      distortion: true
      rotation: true
      channelMix: true
      lowPass: true
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    youtubePlaylistLoadLimit: 6
    playerUpdateInterval: 5
    youtubeSearchEnabled: false # Disable YouTube search
    soundcloudSearchEnabled: true # Enable SoundCloud search
    gc-warnings: false
    trackStuckThresholdMs: 10000
    useSeekGhosting: true

plugins:
  lavasrc:
    providers:
      - "scsearch:%ISRC%" # ISRC provider for SoundCloud
      - "scsearch:%QUERY%" # Direct SoundCloud search
      - "ytsearch:\"%ISRC%\"" # Fallback to YouTube if needed
      - "ytsearch:%QUERY%" # Fallback YouTube search
    sources:
      soundcloud: true
      spotify: false # Disable if no credentials
      applemusic: false # Disable if no credentials
      deezer: false # Disable if no credentials
      yandexmusic: false
      flowerytts: false
      youtube: false # Disable YouTube to force SoundCloud
    soundcloud:
      clientId: "iZIs9mchVcX5lhVRyQGGAYlNPVldzAoX" # Public SoundCloud client ID
      countryCode: "${SOUNDCLOUD_COUNTRY_CODE:US}"
      playlistLoadLimit: 200
      searchMaxResults: 10
    spotify:
      clientId: "${SPOTIFY_CLIENT_ID:}"
      clientSecret: "${SPOTIFY_CLIENT_SECRET:}"
      countryCode: "${SPOTIFY_COUNTRY_CODE:US}"
      playlistLoadLimit: 10
      albumLoadLimit: 10

metrics:
  prometheus:
    enabled: false

sentry:
  dsn: ""

logging:
  level:
    root: INFO
    lavalink: INFO
    com.sedmelluq.discord.lavaplayer: INFO
    com.sedmelluq.discord.lavaplayer.source.soundcloud: DEBUG # Debug SoundCloud specifically
    com.github.topi314.lavasrc: DEBUG # Debug lavasrc plugin
  logback:
    rollingpolicy:
      max-file-size: 25MB
      max-history: 8
