server:
  port: 2333
  address: 0.0.0.0

lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.7.2"
      repository: "https://maven.lavalink.dev/releases"

  server:
    password: "${LAVALINK_PASSWORD:UtaUtaDj}"
    sources:
      youtube: false  # Disabled - handled by plugin
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false
      spotify: false
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    youtubePlaylistLoadLimit: 6
    playerUpdateInterval: 5
    youtubeSearchEnabled: false  # Disabled - handled by plugin
    soundcloudSearchEnabled: true
    gc-warnings: false

plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    # Multiple clients for better anti-bot bypass
    clients:
      - MUSIC
      - ANDROID_TESTSUITE
      - WEB
      - TVHTML5EMBEDDED
    # Optional: YouTube cookies for better success rate
    # DELEGATED_SESSION_ID: "${YOUTUBE_DELEGATED_SESSION_ID:}"
    # VISITOR_DATA: "${YOUTUBE_VISITOR_DATA:}"

metrics:
  prometheus:
    enabled: false

sentry:
  dsn: ""

logging:
  level:
    root: INFO
    lavalink: INFO
    dev.lavalink.youtube: DEBUG
