server:
  port: 2333
  address: 0.0.0.0

lavalink:
  server:
    password: "${LAVALINK_PASSWORD:UtaUtaDj}"
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    youtubePlaylistLoadLimit: 6
    playerUpdateInterval: 5
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: false
    # Enable more verbose error reporting
    trackStuckThresholdMs: 10000
    useSeekGhosting: true

metrics:
  prometheus:
    enabled: false

sentry:
  dsn: ""

logging:
  level:
    root: INFO
    lavalink: DEBUG
    # Enable debug for audio sources
    com.sedmelluq.discord.lavaplayer: DEBUG
    com.sedmelluq.discord.lavaplayer.source: DEBUG
    com.sedmelluq.discord.lavaplayer.source.youtube: DEBUG
    com.sedmelluq.discord.lavaplayer.source.soundcloud: DEBUG
    com.sedmelluq.discord.lavaplayer.source.bandcamp: DEBUG
  logback:
    rollingpolicy:
      max-file-size: 25MB
      max-history: 8
