server:
  port: ${SERVER_PORT:2333}
  address: 0.0.0.0

lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.5.2"
      repository: "https://maven.lavalink.dev/releases"

  server:
    password: "${LAVALINK_PASSWORD:UtaUtaDj}"
    sources:
      # Audio sources configuration - CRITICAL: HTTP must be enabled
      youtube: false  # Disabled - handled by YouTube plugin below
      bandcamp: true
      soundcloud: true
      twitch: false
      vimeo: false
      mixer: false
      http: true  # ESSENTIAL: Enable HTTP for DI.FM streams
      local: false
    filters:
      volume: true
      equalizer: true
      karaoke: true
      timescale: true
      tremolo: true
      vibrato: true
      distortion: true
      rotation: true
      channelMix: true
      lowPass: true
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    trackStuckThresholdMs: 10000
    playerUpdateInterval: 5
    youtubeSearchEnabled: false  # Disabled - handled by YouTube plugin
    soundcloudSearchEnabled: true
    gc-warnings: false
    
    # Resume configuration for better reliability
    resumeKey: "${LAVALINK_RESUME_KEY:uta-dj-bot-railway}"
    resumeTimeout: ${LAVALINK_RESUME_TIMEOUT:60}
    
    ratelimit:
      ipBlocks: []
      excludedIps: []
      strategy: "RotateOnBan"
      searchTriggersFail: true
      retryLimit: -1
      
    # ENHANCED HTTP configuration specifically for DI.FM
    httpConfig:
      proxyHost: ""
      proxyPort: 0
      proxyUser: ""
      proxyPassword: ""
      # Optimized for DI.FM streaming
      connectTimeoutMs: 30000      # Increased for radio streams
      connectionRequestTimeoutMs: 30000
      socketTimeoutMs: 90000       # Increased for continuous streaming
      maxRedirects: 10             # Allow redirects
      # Better user agent for DI.FM compatibility
      userAgent: "Lavalink/4.0.8 (compatible; DI.FM-Player)"
      
    youtubeConfig:
      email: ""
      password: ""

plugins:
  youtube:
    enabled: ${LAVALINK_PLUGINS_ENABLED:true}
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    clients:
      - MUSIC
      - WEB
      - ANDROID_TESTSUITE
      - WEB_REMIX
      - TVHTML5EMBEDDED
    countryCode: "${YOUTUBE_COUNTRY_CODE:US}"

metrics:
  prometheus:
    enabled: false
    endpoint: /metrics

sentry:
  dsn: ""
  environment: ""

logging:
  level:
    root: INFO
    lavalink: INFO
    com.sedmelluq.discord.lavaplayer: INFO
    # IMPORTANT: Enable DEBUG for HTTP stream troubleshooting
    com.sedmelluq.discord.lavaplayer.source.http: DEBUG
    # DI.FM specific logging
    com.sedmelluq.discord.lavaplayer.source.http.HttpAudioSourceManager: DEBUG

  request:
    enabled: true
    includeClientInfo: true
    includeHeaders: false
    includeQueryString: true
    includePayload: true
    maxPayloadLength: 10000

  logback:
    rollingpolicy:
      max-file-size: 25MB
      max-history: 8
