server:
  port: ${SERVER_PORT:2333}
  address: 0.0.0.0

lavalink:
  server:
    password: "${LAVALINK_PASSWORD:UtaUtaDj}"
    sources:
      # Audio sources - enable what you need
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: false
      vimeo: false
      mixer: false
      http: true
      local: false
    filters:
      volume: true
      equalizer: true
      karaoke: true
      timescale: true
      tremolo: true
      vibrato: true
      distortion: true
      rotation: true
      channelMix: true
      lowPass: true
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    trackStuckThresholdMs: 10000
    youtubePlaylistLoadLimit: 6
    playerUpdateInterval: 5
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: false
    ratelimit:
      ipBlocks: []
      excludedIps: []
      strategy: "RotateOnBan"
      searchTriggersFail: true
      retryLimit: -1
    youtubeConfig:
      email: ""
      password: ""

metrics:
  prometheus:
    enabled: false
    endpoint: /metrics

sentry:
  dsn: ""
  environment: ""

logging:
  level:
    root: INFO
    lavalink: INFO

  request:
    enabled: true
    includeClientInfo: true
    includeHeaders: false
    includeQueryString: true
    includePayload: true
    maxPayloadLength: 10000

  logback:
    rollingpolicy:
      max-file-size: 25MB
      max-history: 8
