server:
  port: 2333
  address: 0.0.0.0

lavalink:
  server:
    password: "${LAVALINK_PASSWORD:UtaUtaDj}"
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false
      spotify: false
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    opusEncodingQuality: 10
    resamplingQuality: LOW
    trackStuckThresholdMs: 10000
    useSeekGhosting: true
    youtubePlaylistLoadLimit: 6
    playerUpdateInterval: 5
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: false
    
    # Enhanced YouTube configuration for anti-bot
    ratelimit:
      ipBlocks: ["1.0.0.0/8", "127.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16", "fd00::/8"]
      excludedIps: ["127.0.0.1", "::1"]
      strategy: "RotateOnBan"
      searchTriggersFail: true
      retryLimit: -1
      
    youtubeConfig:
      email: ""
      password: ""
      PAPISID: ""
      PSID: ""

metrics:
  prometheus:
    enabled: false

sentry:
  dsn: ""

logging:
  level:
    root: INFO
    lavalink: INFO
