server:
  port: ${SERVER_PORT:2333}
  address: 0.0.0.0

lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.5.2"
      repository: "https://maven.lavalink.dev/releases"

  server:
    password: "${LAVALINK_PASSWORD:UtaUtaDj}"
    sources:
      # Audio sources configuration - CRITICAL: HTTP must be enabled
      youtube: false  # Disabled - handled by YouTube plugin below
      bandcamp: true
      soundcloud: true
      twitch: false
      vimeo: false
      mixer: false
      http: true  # ESSENTIAL: Enable HTTP for radio streams
      local: false
    filters:
      volume: true
      equalizer: true
      karaoke: true
      timescale: true
      tremolo: true
      vibrato: true
      distortion: true
      rotation: true
      channelMix: true
      lowPass: true
    bufferDurationMs: 2000    # INCREASED: Better for radio streams
    frameBufferDurationMs: 8000  # INCREASED: Prevent audio drops
    trackStuckThresholdMs: 15000  # INCREASED: More patience for radio
    playerUpdateInterval: 5
    youtubeSearchEnabled: false  # Disabled - handled by YouTube plugin
    soundcloudSearchEnabled: true
    gc-warnings: false
    
    # Resume configuration for better reliability - FIXED KEYS
    resumeKey: "${LAVALINK_RESUME_KEY:uta-dj-bot-railway-v2}"
    resumeTimeout: ${LAVALINK_RESUME_TIMEOUT:120}  # INCREASED timeout
    
    ratelimit:
      ipBlocks: []
      excludedIps: []
      strategy: "RotateOnBan"
      searchTriggersFail: true
      retryLimit: -1
      
    # ENHANCED HTTP configuration - FIXED FOR RADIO STREAMS
    httpConfig:
      proxyHost: ""
      proxyPort: 0
      proxyUser: ""
      proxyPassword: ""
      # Radio stream optimized settings
      connectTimeoutMs: 20000      # Reduced but reasonable
      connectionRequestTimeoutMs: 20000
      socketTimeoutMs: 60000       # Radio streams need longer socket timeout
      maxRedirects: 8              # Allow reasonable redirects
      # Better user agent for compatibility
      userAgent: "Lavalink/4.0.8 (UTA-DJ-Bot; +https://github.com/utabot)"
      
    youtubeConfig:
      email: ""
      password: ""

plugins:
  youtube:
    enabled: ${LAVALINK_PLUGINS_ENABLED:true}
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    clients:
      - MUSIC
      - WEB
      - ANDROID_TESTSUITE
      - WEB_REMIX
      - TVHTML5EMBEDDED
    countryCode: "${YOUTUBE_COUNTRY_CODE:US}"

metrics:
  prometheus:
    enabled: false
    endpoint: /metrics

sentry:
  dsn: ""
  environment: ""

logging:
  level:
    root: WARN              # REDUCED: Less noise in logs
    lavalink: INFO
    com.sedmelluq.discord.lavaplayer: INFO
    # HTTP stream debugging - ONLY when needed
    com.sedmelluq.discord.lavaplayer.source.http: INFO  # Changed from DEBUG
    com.sedmelluq.discord.lavaplayer.source.http.HttpAudioSourceManager: INFO

  request:
    enabled: true
    includeClientInfo: false   # REDUCED: Less log spam
    includeHeaders: false
    includeQueryString: false  # REDUCED: Less log spam
    includePayload: false      # REDUCED: Less log spam
    maxPayloadLength: 1000     # REDUCED: Less log spam

  logback:
    rollingpolicy:
      max-file-size: 10MB      # REDUCED: Save disk space on Railway
      max-history: 3           # REDUCED: Save disk space
