server:
  port: ${SERVER_PORT:2333}
  address: 0.0.0.0

lavalink:
  server:
    password: "${LAVALINK_PASSWORD:UtaUtaDj}"
    sources:
      youtube: true  # ✅ ENABLED - YouTube support
      bandcamp: true  # ✅ ENABLED - Better compatibility
      soundcloud: true  # ✅ ENABLED - SoundCloud support
      twitch: false
      vimeo: false
      http: true
      local: false
    filters:
      volume: true
      equalizer: true
      karaoke: true
      timescale: true
      tremolo: true
      vibrato: true
      distortion: true
      rotation: true
      channelMix: true
      lowPass: true
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    trackStuckThresholdMs: 10000
    youtubePlaylistLoadLimit: 6
    playerUpdateInterval: 5
    youtubeSearchEnabled: true  # ✅ ENABLED - YouTube search
    soundcloudSearchEnabled: true  # ✅ ENABLED - SoundCloud search
    gc-warnings: false
    useSeekGhosting: true
    # Enhanced HTTP streaming configuration for better stability
    httpConfig:
      proxyHost: ""
      proxyPort: 0
      proxyUser: ""
      proxyPassword: ""
      # ✅ ADDED: Connection timeout settings
      connectionTimeout: 30000
      readTimeout: 60000

# ✅ ADDED: Connection keep-alive settings
plugins:
  # YouTube source plugin for better reliability
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true

# ✅ ENHANCED: Better metrics and monitoring
metrics:
  prometheus:
    enabled: false
    endpoint: /metrics

sentry:
  dsn: ""

# ✅ IMPROVED: More detailed logging for debugging
logging:
  level:
    root: INFO
    lavalink: INFO
    com.sedmelluq.discord.lavaplayer: INFO
    com.sedmelluq.discord.lavaplayer.source.http: INFO
    # ✅ ADDED: Better WebSocket logging
    io.undertow.websockets: DEBUG
  logback:
    rollingpolicy:
      max-file-size: 25MB
      max-history: 8

# ✅ ADDED: JVM settings for better memory management
management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      show-details: always
