server:
  port: ${SERVER_PORT:2333}
  address: 0.0.0.0

lavalink:
  server:
    password: ${LAVALINK_PASSWORD:UtaUtaDj}
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false
    plugins:
      - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.3.0"
        snapshot: false
        repositories:
          - "https://maven.topi.wtf/releases"
          - "https://maven.lavalink.dev/releases"
  plugins:
    lavasrc:
      providers: [ "youtube", "yandex" ]
      spotify:
        enabled: true
        clientId: ${SPOTIFY_CLIENT_ID:}
        clientSecret: ${SPOTIFY_CLIENT_SECRET:}
        countryCode: "US"

logging:
  level:
    root: INFO
